services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=db
      - DB_NAME=family_recipes
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
  
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=family_recipes
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  
  cache:
    image: redis:7.0-alpine
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  redis-data: