services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    depends_on:
      - db
      - cache
      - minio
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_SECURE=${MINIO_SECURE}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
  
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  
  cache:
    image: redis:7.0-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - "9000:9000"  # S3 API Port
      - "9001:9001"  # Web Console (UI) Port
      
    # Environment Variables for root access
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_SECURE=${MINIO_SECURE}

    command: server /data --console-address ":9001"

    volumes:
      - ./minio-data:/data

    restart: always

volumes:
  redis-data: