# Generated by Django 5.2.7 on 2025-10-23 00:47

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_category_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, storage=core.storage.MinIOStorage(), upload_to="recipes/"
            ),
        ),
    ]
