# Generated by Django 5.2.7 on 2025-10-23 01:03

import core.storage
import recipe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storage.MinIOStorage(),
                upload_to=recipe.models.recipe_image_upload_path,
            ),
        ),
    ]
