---
name: Checks

on:
  push:
    branches: [main, develop, dev/*]
  pull_request:
    branches: [main, develop]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test
        env:
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          docker compose run --rm api sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Flake8
        run: |
          docker compose run --rm api sh -c "flake8"
